name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - dev

permissions:
  contents: write

concurrency:
  group: gh-pages-workflow
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Lint check
        run: |
          NODE_ENV=development npm install
          npm run lint:check

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy master branch to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          folder: dist
          repository-name: scerka-soft/hub
          branch: gh-pages
          target-folder: wakamaifondue
          commit-message: Update wakamaifondue
          clean: true